In [1]:
import pandas as pd

In [12]:
df = pd.read_csv("combined_years.csv")

In [13]:
df = df.drop(columns=["Unnamed: 0"])

In [14]:
df

,date,network,duration(s),llm_text,show_tag,year
0,2018-01-01 11:16:46,FOXNEWSW,2,UMP LAYS OUT DEMANDS FOR DACA,FOX Friends,2018
1,2018-01-01 11:18:00,FOXNEWSW,3,IMMIGRATION ON THE AGENDA,FOX Friends,2018
2,2018-01-01 11:19:22,FOXNEWSW,25,DEADLINE ON DACA,FOX Friends,2018
3,2018-01-01 11:19:59,FOXNEWSW,3,DACA IN THE NEW YEAR,FOX Friends,2018
4,2018-01-01 13:12:39,FOXNEWSW,9,WANT TO SEE BORDER WALL BUILT,FOX Friends,2018
...,...,...,...,...,...,...
83049,2026-02-27 23:53:54,MSNOW,2,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...,The Beat With Ari Melber,2026
83050,2026-02-28 00:25:50,BBCNEWS,4,Iran after latest talks on immigration reforms...,BBC News,2026
83051,2026-02-28 04:15:16,FOXNEWSW,3,BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,Fox News at Night,2026
83052,2026-02-28 04:19:48,FOXNEWSW,4,US OLYMPIAN DEFENDS LEGAL IMMIGRATION,Fox News at Night,2026
83053,2026-02-28 05:18:32,CNNW,6,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...,The Story Is With Elex Michaelson,2026

In [ ]:
frame_words = {'Victims': {'languish (v)', 'sanctuary (n)', 'relief (n)', 'feed (v)',
                           'survivor (n)', 'compassion (n)', 'hope (v)', 'suffering (n)',
                           'help (v)', 'acceptance (n)', 'persecute (v)', 'aid (v)',
                           'deserve (v)', 'amnesty (n)', 'hopeful (j)','reward (v)',
                           'helpless (j)', 'refugee (n)', 'assist (v)', 'struggle (n)',
                           'unfortunate (j)', 'flee (v)', 'aid (n)', 'victim (n)',
                           'rescue (v)', 'afflict (v)', 'battered (j)', 'penniless (j)',
                           'prejudice (n)', 'asylum (n)', 'orphan (n)', 'desperate (j)',
                           'plight (n)', 'exploit (v)', 'humanitarian (j)',
                           'refuge (n)', 'welcome (v)', 'tragedy (n)',
                           'shelter (v)', 'impoverished (j)', 'assisted (j)',
                           'persecution (n)', 'assistance (n)', 'escape (v)'},
               'Contribution': {'veteran (n)', 'attract (v)', 'contribute (v)',
                                'ability (n)', 'industrious (j)', 'friendly (j)',
                                'hardworking (j)', 'selfsufficiency (n)', 'worthy (j)',
                                'genuine (j)', 'sturdy (j)', 'patent (n)',
                                'enlist (v)', 'build (v)', 'qualified (j)',
                                'loyal (j)', 'lawabide (v)', 'desirable (j)',
                                'contribution (n)', 'highskilled (j)', 'gain (v)',
                                'enrich (v)', 'hero (n)'},
               'Family': {'son (n)', 'kid (n)', 'girl (n)', 'grandchild (n)',
                          'marriage (n)', 'descendent (n)', 'husband (n)',
                          'granddaughter (n)', 'marry (v)', 'generation (n)',
                          'child (n)', 'ancestor (n)', 'wife (n)', 'neighbor (n)',
                          'orphan (n)', 'family (n)', 'familybased (j)', 'household (n)',
                          'boy (n)', 'spouse (n)', 'relative (n)', 'parent (n)',
                          'grandson (n)', 'neighborhood (n)', 'relative (j)',
                          'familysponsored (j)', 'grandparent (n)', 'descendant (n)',
                          'daughter (n)'},
               'Culture': {'diverse (j)', 'foreigner (n)', 'integration (n)',
                           'heritage (n)', 'society (n)', 'race (n)',
                           'citizenship (v)', 'americanization (n)', 'integrate (v)',
                           'tradition (n)', 'ethnic (j)', 'christian (j)', 'flag (n)',
                           'culture (n)', 'diversity (n)', 'nation (n)', 'background (n)',
                           'assimilate (v)', 'language (n)', 'assimilation (n)'},
               'Deficient': {'objectionable (j)', 'slacker (n)', 'drunk (j)',
                             'aidsinfected (j)', 'unskilled (j)', 'undesirable (j)',
                             'diseased (j)', 'insane (j)', 'unfit (j)', 'insane (n)',
                             'cheap (j)', 'illiterate (j)', 'ignorant (j)', 'illiteracy (n)'},
               'Crime': {'steal (v)', 'bootlegger (n)', 'absconder (n)',
                         'imprison (v)', 'incarceration (n)', 'illegal (j)', 'convict (v)',
                         'inmate (n)', 'fugitive (j)', 'terrorist (n)', 'apprehend (v)',
                         'imprisonment (n)', 'arrest (v)', 'criminal (j)',
                         'prosecution (n)', 'smuggler (n)', 'noncriminal (j)', 'felon (n)',
                         'detain (v)', 'jail (v)', 'arrest (n)', 'detainee (n)',
                         'smuggling (n)', 'prosecute (v)', 'violent (j)', 'terrorist (j)',
                         'parole (n)', 'gang (n)', 'incarcerate (v)', 'unlawful (j)',
                         'smuggle (v)', 'offense (n)', 'parole (v)', 'criminalize (v)',
                         'criminal (n)', 'capture (v)'},
               'Threat': {'infect (v)', 'aidsinfected (j)', 'combatant (n)',
                          'enemy (n)', 'attack (v)', 'invasion (n)', 'danger (n)',
                          'diseased (j)', 'terrorist (n)', 'attack (n)', 'blame (v)',
                          'dangerous (j)', 'overrun (n)', 'threaten (v)', 'problem (n)',
                          'violent (j)', 'terrorist (j)', 'gang (n)', 'anarchist (n)',
                          'belligerent (n)', 'horde (n)', 'apprehension (n)'},
               'Economic': {'sale (n)', 'fund (n)', 'agricultural (j)', 'compete (v)',
                            'cent (n)', 'reimbursement (n)', 'funding (n)',
                            'bank (n)', 'ownership (n)', 'purchase (v)', 'finance (v)',
                            'buy (v)', 'specie (n)', 'property (n)', 'taxpayer (n)',
                            'owner (n)', 'coin (v)', 'allocation (n)', 'cost (v)',
                            'economic (j)', 'cash (n)', 'corporation (n)', 'tax (n)',
                            'taxpaye (v)', 'competition (n)', 'pay (v)', 'investor (n)',
                            'workforce (n)', 'tax (v)', 'budget (n)'},
               'Labor': {'agricultural (j)', 'compete (v)', 'unskilled (j)',
                         'employer (n)', 'hiring (n)', 'miner (n)', 'employmentbased (j)',
                         'nurse (n)', 'hire (v)', 'crewman (n)', 'employment (n)',
                         'farmworker (n)', 'tailor (n)', 'employee (n)', 'worker (n)',
                         'competition (n)', 'workforce (n)', 'laborer (n)', 'employ (v)'},
               'Legality': {'legitimate (j)', 'citizenship (n)', 'hearing (n)',
                            'status (n)', 'undocumented (j)', 'law (n)', 'legal (j)',
                            'license (n)', 'legalized (j)', 'lawful (j)',
                            'verification (n)', 'eligible (j)', 'illegal (j)',
                            'permanent (j)', 'citizenship (v)', 'naturalize (v)',
                            'registration (n)', 'naturalization (n)', 'amnesty (n)',
                            'inadmissible (j)', 'applicant (n)', 'exemption (n)',
                            'visa (n)', 'ineligible (j)', 'qualify (v)', 'sponsor (v)',
                            'registered (j)', 'prosecute (v)', 'identification (n)',
                            'authorize (v)', 'unnaturalized (j)',
                            'authorization (n)', 'sponsor (n)',
                            'unauthorized (j)', 'overstay (v)',
                            'unlawful (j)', 'eligibility (n)', 'legalize (v)',
                            'adjudication (n)', 'familysponsored (j)', 'legalization (n)',
                            'application (n)'},
               'Quantity': {'estimated (j)', 'much (j)', 'bunch (n)', 'thousand (n)',
                            'most (j)', 'percentage (n)', 'many (j)', 'million (n)',
                            'entire (j)', 'count (v)', 'number (v)', 'mass (n)',
                            'crowd (n)', 'additional (j)', 'twothird (n)', 'counting (n)',
                            'count (n)', 'total (n)', 'total (j)', 'flock (v)',
                            'increase (v)', 'statistic (n)', 'boatload (n)',
                            'more (j)', 'shipload (n)', 'estimate (v)', 'cap (n)',
                            'majority (n)', 'masse (n)', 'bulk (n)', 'fraction (n)',
                            'sum (n)', 'estimate (n)', 'number (n)', 'proportion (n)',
                            'horde (n)'},
               'Flood/Tide': {'stream (v)', 'flow (n)', 'absorb (v)', 'flood (n)',
                              'wave (n)', 'spill (v)', 'inflow (n)', 'trickle (n)',
                              'influx (n)', 'surge (n)', 'fill (v)', 'pour (v)', 'stream (n)',
                              'absorption (n)', 'outflow (n)', 'flow (v)', 'flood (v)',
                              'tide (n)', 'drain (v)'},
               'Exclusion': {'reject (v)', 'limitation (n)', 'requirement (n)',
                             'deportable (j)', 'removable (j)', 'deport (v)', 'shut (v)',
                             'stop (v)', 'prohibition (n)', 'interdict (v)', 'screen (v)',
                             'debar (v)', 'restrict (v)', 'deported (j)', 'bar (v)',
                             'quota (n)', 'expel (v)', 'inadmissible (j)',
                             'deportation (n)', 'deter (v)', 'vet (v)', 'exclude (v)',
                             'allow (v)', 'interdiction (n)', 'ban (v)', 'detain (v)',
                             'removal (n)', 'ceiling (n)', 'forbid (v)', 'exclusion (n)',
                             'deny (v)', 'excludable (j)', 'cap (n)', 'vetting (n)',
                             'bar (n)', 'prevent (v)', 'expulsion (n)', 'inspect (v)',
                             'prohibit (v)', 'unauthorized (j)', 'overstay (v)',
                             'screening (n)', 'limit (n)', 'admissibility (n)',
                             'eligibility (n)', 'limit (v)', 'ban (n)', 'restriction (n)',
                             'criterion (n)'},
               'Migration': {'enter (v)', 'destination (n)', 'flight (n)', 'ship (v)',
                             'route (n)', 'seaman (n)', 'relocate (v)', 'passenger (n)',
                             'incoming (j)', 'leave (v)', 'relocation (n)', 'exodus (n)',
                             'arrival (n)', 'land (v)', 'convoy (n)', 'depart (v)',
                             'settle (v)', 'landing (n)', 'move (v)', 'port (n)',
                             'travel (v)', 'resettle (v)', 'arrive (v)', 'displacement (n)',
                             'settlement (n)', 'cross (v)', 'station (n)', 'resettling (n)',
                             'return (v)', 'migration (n)', 'movement (n)', 'coming (n)',
                             'reenter (v)', 'departure (n)', 'entrance (n)', 'depot (n)',
                             'boatload (n)', 'shipload (n)', 'emigrate (v)',
                             'resettlement (n)', 'migrate (v)', 'come (v)',
                             'return (n)', 'transport (v)', 'passage (n)',
                             'immigrate (v)', 'entry (n)'},
               'Background': {'immigration (n)'}
               }


def get_tagged_frame_terms():
    return frame_words


# replacements to make to account for the different preprocessing of Gentzkow and USCR (hyphenation, etc.)
frame_queries = {'self sufficiency': 'selfsufficiency',
                      'law abide': 'lawabide',
                      'high skilled': 'highskilled',
                      'family based': 'familybased',
                      'family sponsored': 'familysponsored',
                      'aids infected': 'aidsinfected',
                      'employment based': 'employmentbased',
                      'farm worker': 'farmworker',
                      'two third': 'twothird',
                      }

frame_replacements = {'self (n) sufficiency (n)': 'selfsufficiency (n)',
                      'law (n) abide (v)': 'lawabide (v)',
                      'high (j) skilled (j)': 'highskilled (j)',
                      'family (n) based (n)': 'familybased (j)',
                      'family (n) sponsored (j)': 'familysponsored ()',
                      'aids (n) infected (j)': 'aidsinfected (j)',
                      'employment (n) based (n)': 'employmentbased (j)',
                      'farm (n) worker (n)': 'farmworker (n)',
                      'farm (v) worker (n)': 'farmworker (n)',
                      'two (c) third (n)': 'twothird (n)',
                      }


def get_frame_replacements():
    return frame_replacements

In [136]:

# Countries that have represented at least 1% of the US foreign-born population in some decadal census

countries = {'Ireland': ['Ireland'],
             'Germany': ['Germany'],
             'Mexico': ['Mexico'],
             'Italy': ['Italy'],
             'England': ['England'],
             'Canada': ['Canada'],
             'Russia': ['Russia', 'USSR'],
             'Poland': ['Poland'],
             'China': ['China'],
             'India': ['India'],
             'Sweden': ['Sweden'],
             'Austria': ['Austria'],
             'Philippines': ['Philippines', 'Philippine'],
             'Cuba': ['Cuba'],
             'Hungary': ['Hungary'],
             'Norway': ['Norway'],
             'Czechoslovakia': ['Czechoslovakia', 'Czech', 'Slovakia', 'Slovak'],
             'Vietnam': ['Vietnam'],
             'Scotland': ['Scotland'],
             'El Salvador': ['El Salvador'],
             'Korea': ['Korea'],
             'France': ['France'],
             'Dominican Republic': ['Dominican'],
             'Guatemala': ['Guatemala'],
             'Greece': ['Greece'],
             'Colombia': ['Colombia'],
             'Jamaica': ['Jamaica'],
             'Yugoslavia': ['Yugoslavia', 'Serbia', 'Croatia', 'Macedonia', 'Bosnia', 'Herzegovina', 'Montenegro'],
             'Honduras': ['Honduras'],
             'Japan': ['Japan'],
             'Haiti': ['Haiti'],
             'Portugal': ['Portugal'],
             'Denmark': ['Denmark'],
             'Lithuania': ['Lithuania'],
             'Switzerland': ['Switzerland'],
             'Wales': ['Wales'],
             'Taiwan': ['Taiwan'],
             'Netherlands': ['Netherlands', 'Holland'],
             'Brazil': ['Brazil'],
             'Finland': ['Finland'],
             'Iran': ['Iran'],
             'Ecuador': ['Ecuador'],
             'Venezuela': ['Venezuela'],
             'Romania': ['Romania', 'Rumania', 'Roumania'],
             'Peru': ['Peru']
             }


# Regions excluding England, France, Canada, and India, due to potential for name confusion
regions = {'Latin America': ['Mexico', 'Cuba', 'El Salvador', 'Guatemala', 'Colombia', 'Honduras', 'Ecuador', 'Venezuela', 'Peru'],
           'Europe': ['Ireland', 'Germany', 'Italy', 'Russia', 'USSR', 'Poland', 'Sweden', 'Austria', 'Hungary', 'Norway', 'Czechoslovakia', 'Czech', 'Slovakia', 'Slovak', 'Greece', 'Yugoslavia', 'Serbia', 'Croatia', 'Macedonia', 'Bosnia', 'Herzegovina', 'Montenegro', 'Portugal', 'Denmark', 'Lithuania', 'Switzerland', 'Netherlands', 'Holland', 'Finland', 'Romania', 'Rumania', 'Roumania'],
           'Asia': ['China', 'Philippines', 'Philippine', 'Vietnam', 'Korea', 'Japan', 'Taiwan']
           }

def get_countries():
    return countries


nationalities = {'Ireland': ['Irish', 'Irishman', 'Irishmen'],
                 'Germany': ['German', 'Germans'],
                 'Mexico': ['Mexican', 'Mexicans'],
                 'Italy': ['Italian', 'Italians'],
                 'England': ['Englishman', 'Englishmen'],
                 'Canada': ['Canadian', 'Canadians'],
                 'Russia': ['Russian', 'Russians'],
                 'Poland': ['Polish', 'Poles'],
                 'China': ['Chinese', 'Chinaman', 'Chinamen'],
                 'India': ['Indian', 'Indians'],
                 'Sweden': ['Swedish', 'Swedes'],
                 'Austria': ['Austrian', 'Austrians'],
                 'Philippines': ['Filipino', 'Filipinos', 'Filipina', 'Filipinas'],
                 'Cuba': ['Cuban', 'Cubans'],
                 'Hungary': ['Hungarian', 'Hungarians'],
                 'Norway': ['Norwegian', 'Norwegians'],
                 'Czechoslovakia': ['Czech', 'Czechs', 'Slovak', 'Slovaks', 'Slovakian', 'Slovakians', 'Czechoslovakian', 'Czechoslovakians'],
                 'Vietnam': ['Vietnamese'],
                 'Scotland': ['Scottish', 'Scots', 'Scotsman', 'Scotsmen'],
                 'El Salvador': ['Salvadoran', 'Salvadorans', 'Salvadorian', 'Salvadorians'],
                 'Korea': ['Korean', 'Koreans'],
                 'France': ['Frenchman', 'Frenchmen'],
                 'Dominican Republic': ['Dominican', 'Dominicans'],
                 'Guatemala': ['Guatemalan', 'Guatemalans'],
                 'Greece': ['Greek', 'Greeks'],
                 'Colombia': ['Colombian', 'Colombians'],
                 'Jamaica': ['Jamaican', 'Jamaicans'],
                 'Yugoslavia': ['Yugoslavian', 'Yugoslavians', 'Serbian', 'Serbians', 'Serb', 'Serbs', 'Croatian', 'Croatians', 'Croat', 'Croats', 'Macedonian', 'Macedonians', 'Bosnian', 'Bosnians'],
                 'Honduras': ['Honduran', 'Hondurans'],
                 'Japan': ['Japanese', 'Jap', 'Japs'],
                 'Haiti': ['Haitian', 'Haitians'],
                 'Portugal': ['Portuguese'],
                 'Denmark': ['Danish', 'Danes'],
                 'Lithuania': ['Lithuanian', 'Lithuanians'],
                 'Switzerland': ['Swiss'],
                 'Wales': ['Welsh', 'Welshman', 'Welshmen'],
                 'Taiwan': ['Taiwanese'],
                 'Netherlands': ['Dutch'],
                 'Brazil': ['Brazilian', 'Brazilians'],
                 'Finland': ['Finnish', 'Finn', 'Finns',],
                 'Iran': ['Iranian', 'Iranians'],
                 'Ecuador': ['Ecuadorian', 'Ecuadorians'],
                 'Venezuela': ['Venezuelan', 'Venezuelans'],
                 'Romania': ['Romanian', 'Romanians', 'Rumanian', 'Rumanians', 'Roumania', 'Roumanian', 'Roumanians'],
                 'Peru': ['Peruvian', 'Peruvians']
                 }

regionalities = {'Latin America': ['Mexican', 'Mexicans', 'Cuban', 'Cubans', 'Salvadoran', 'Salvadorans', 'Salvadorian', 'Salvadorians', 'Guatemalan', 'Guatemalans', 'Colombian', 'Colombians', 'Honduran', 'Hondurans', 'Ecuadorian', 'Ecuadorians', 'Venezuelan', 'Venezuelans', 'Peruvian', 'Peruvians', 'Hispanic', 'Hispanics', 'Latino', 'Latinos', 'Latina', 'Latinas'],
                 'Europe': ['Irish', 'Irishman', 'Irishmen', 'German', 'Germans', 'Italian', 'Italians', 'Russian', 'Russians', 'Polish', 'Poles', 'Swedish', 'Swedes', 'Austrian', 'Austrians', 'Hungarian', 'Hungarians', 'Norwegian', 'Norwegians', 'Czech', 'Czechs', 'Slovak', 'Slovaks', 'Slovakian', 'Slovakians', 'Czechoslovakian', 'Czechoslovakians', 'Greek', 'Greeks', 'Yugoslavian', 'Yugoslavians', 'Serbian', 'Serbians', 'Serb', 'Serbs', 'Croatian', 'Croatians', 'Croat', 'Croats', 'Macedonian', 'Macedonians', 'Bosnian', 'Bosnians', 'Portuguese', 'Danish', 'Danes', 'Lithuanian', 'Lithuanians', 'Swiss', 'Dutch', 'Finnish', 'Finn', 'Finns', 'Romanian', 'Romanians', 'Rumanian', 'Rumanians', 'Roumania', 'Roumanian', 'Roumanians'],
                 'Asia': ['Chinese', 'Chinaman', 'Chinamen', 'Filipino', 'Filipinos', 'Filipina', 'Filipinas', 'Vietnamese', 'Korean', 'Koreans', 'Japanese', 'Jap', 'Japs', 'Taiwanese']
                }

def get_nationalities():
    return nationalities


def get_regions_and_regionalities():
    return regions, regionalities


def add_american(nationalities):
    # add American and Americans to appropriate terms, and create replacements
    american_terms = {}
    substitutions = {}
    for nationality, terms in nationalities.items():
        #american_terms[nationality] = terms.copy()
        american_terms[nationality] = [terms[0] + 'American', terms[0] + 'Americans']
        substitutions[terms[0] + ' ' + 'American'] = terms[0] + 'American'
        substitutions[terms[0] + ' ' + 'Americans'] = terms[0] + 'Americans'
        substitutions[terms[0] + '-American'] = terms[0] + 'American'
        substitutions[terms[0] + '-Americans'] = terms[0] + 'Americans'
        for term in terms[1:]:
            if term[-1] != 's' and term[-3:] != 'men' and term[-3:] != 'man':
                american_terms[nationality].extend([term + 'American', term + 'Americans'])
                substitutions[term + ' ' + 'American'] = term + 'American'
                substitutions[term + ' ' + 'Americans'] = term + 'Americans'
                substitutions[term + '-American'] = term + 'American'
                substitutions[term + '-Americans'] = term + 'Americans'
    return american_terms, substitutions


early_chinese_terms = {'china', 'chinese', 'chinamen', 'chinaman', 'indochina', 'indochinese',
                       'asia', 'asian', 'asians', 'asiatic', 'asiatics',
                       'orient', 'oriental', 'orientals', 'celestial', 'celestials',
                       'cooly', 'coolie', 'coolys', 'coolies',
                       'mongolian', 'mongolians', 'mongol', 'mongols'}

european_countries = {'Ireland',
                      'Germany',
                      'Italy',
                      'England',
                      'Poland',
                      'Sweden',
                      'Austria',
                      'Hungary',
                      'Norway',
                      'Czechoslovakia',
                      'Scotland',
                      'France',
                      'Greece',
                      'Yugoslavia',
                      'Portugal',
                      'Denmark',
                      'Lithuania',
                      'Switzerland',
                      'Wales',
                      'Netherlands',
                      'Finland',
                      'Romania'}

modern_mexican_terms = {'mexico',
                        'mexican',
                        'mexicans',
                        'wetback',
                        'wetbacks',
                        'bracero',
                        'braceros',
                        'mexicanamerican',
                        'mexicanamericans'}


modern_hispanic_terms = {'mexico',
                        'mexican',
                        'mexicans',
                        'wetback',
                        'wetbacks',
                        'bracero',
                        'braceros',
                        'mexicanamerican',
                        'mexicanamericans',
                        'hispanic',
                        'hispanics',
                        'latino',
                        'latinos',
                        'latina',
                        'latinas',
                        'hispanicamerican',
                        'hispanicamericans',
                        'cuba',
                        'cuban',
                        'cubanamerican',
                        'cubanamericans',
                        'cubans',
                        'salvador',
                        'salvadorans',
                        'salvadorian',
                        'salvadorians',
                        'guatemala',
                        'guatemalan',
                        'guatemalans',
                        'colombia',
                        'colombian',
                        'colombians',
                        'honduras',
                        'honduran',
                        'hondurans',
                        'ecuador',
                        'ecuadorian',
                        'ecuadorians',
                        'venezuela',
                        'venezuelan',
                        'venezuelans',
                        'peru',
                        'peruvian',
                        'peruvians'}


def get_subset_terms():
    return early_chinese_terms, european_countries, modern_mexican_terms


def get_modern_hispanic_terms():
    return modern_hispanic_terms

In [133]:
metaphor_terms = {
    'water': ['flood', 'floods', 'flooding', 'river', 'rivers', 'stream', 'stream', 'tide', 'tides', 'water', 'waters', 'ocean', 'oceans', 'wave', 'waves'],
    'animal': ['animal', 'alien', 'aliens', 'animals', 'beast', 'beasts', 'sheep', 'herd', 'herds', 'hog', 'hogs', 'pig', 'pigs', 'livestock', 'dog', 'dogs', 'brute', 'brutes', 'horse', 'horses', 'cow', 'cows', 'cattle'],
    'vermin': ['rat', 'rats', 'vermin', 'worm', 'worms', 'bug', 'bugs', 'parasite', 'parasites', 'lice', 'insect', 'insects', 'pest', 'pests', 'flea', 'fleas', 'leech', 'leeches', 'rodent', 'rodents', 'infestation', 'infestations'],
    'disease': ['disease', 'diseases', 'virus', 'viruses', 'infection', 'infections', 'illness', 'illnesses'],
    'cargo': ['thing', 'things', 'object', 'objects', 'cargo', 'cargoes', 'goods', 'tonnage', 'merchandise', 'item', 'items', 'commodities', 'packages', 'products', 'baggage', 'shipment', 'shipments', 'stuff', 'material'],
    'machines': ['machine', 'machines', 'machinery', 'equipment', 'hardware', 'engine', 'engines', 'tool', 'tools']
 }

def get_metaphor_terms():
    return metaphor_terms

In [ ]:
# find the framing word of the chyron (if any, or a list if multiple)

In [ ]:
# find the immigrant group of the chyron (if any, or a list if multiple)

In [46]:
from tqdm import tqdm
import json
import nltk
from collections import Counter, defaultdict

In [125]:
metaphor_terms = get_metaphor_terms()
metaphor_term_sets = {}
for metaphor, terms in metaphor_terms.items():
    metaphor_term_sets[metaphor] = set(terms)

In [126]:
outlines_by_metaphor = defaultdict(list)
term_counter_by_metaphor = defaultdict(Counter)

In [127]:
# find any metaphor language in the chyron (if any, or a list if multiple)
# def find_metaphor(df):
lines = df['llm_text']
for line in tqdm(lines):

    tokens = list(nltk.word_tokenize(line.lower()))
    # print(tokens)

    # for sent_i, orig_tokens in enumerate(tokens):
    for metaphor, target_terms in metaphor_term_sets.items():
        # convert to lower case and do an initial filter
        # lower_tokens = [t.lower() for t in orig_tokens]
        # print(tokens)
        if len(set(tokens).intersection(target_terms)) > 0:

            # Save the sentence with metadata
            outlines_by_metaphor[metaphor].append({'sent_index': sent_i, 'chyron': line})
            # Keep track of which terms are found most frequently
            term_counter_by_metaphor[metaphor].update(set(tokens).intersection(target_terms))

100%|██████████| 83054/83054 [00:03<00:00, 21988.29it/s]

In [61]:
term_counter_by_metaphor

defaultdict(collections.Counter,
            {'cargo': Counter({'thing': 938,
                      'things': 707,
                      'goods': 639,
                      'items': 225,
                      'products': 162,
                      'objects': 154,
                      'stuff': 128,
                      'object': 128,
                      'cargo': 110,
                      'shipments': 98,
                      'material': 68,
                      'packages': 66,
                      'item': 56,
                      'shipment': 25}),
             'machines': Counter({'tool': 602,
                      'equipment': 191,
                      'engines': 107,
                      'tools': 74,
                      'machine': 58}),
             'animal': Counter({'animals': 878,
                      'beast': 613,
                      'horse': 470,
                      'dog': 301,
                      'horses': 223,
                      'dogs': 185,
                      'animal': 115,
                      'cow': 96,
                      'cows': 15,
                      'livestock': 15}),
             'water': Counter({'wave': 4032,
                      'flood': 2533,
                      'water': 1633,
                      'river': 983,
                      'flooding': 762,
                      'waters': 578,
                      'waves': 412,
                      'stream': 364,
                      'floods': 164,
                      'rivers': 94,
                      'tide': 74,
                      'ocean': 44}),
             'disease': Counter({'virus': 901,
                      'disease': 486,
                      'illness': 312,
                      'diseases': 127,
                      'infections': 114,
                      'infection': 102,
                      'illnesses': 76}),
             'vermin': Counter({'lice': 222,
                      'bugs': 81,
                      'infestation': 70,
                      'vermin': 36,
                      'parasite': 17,
                      'bug': 15})})

In [128]:
lines = df['llm_text']
yes_no_dehumanizing = []
metaphor_category = []

outlines_by_metaphor = defaultdict(list)
term_counter_by_metaphor = defaultdict(Counter)

for i, line in enumerate(tqdm(lines)):

    tokens = list(nltk.word_tokenize(line.lower()))
    is_dehumanizing = False
    category = pd.NA
    # print(tokens)

    # for sent_i, orig_tokens in enumerate(tokens):
    for metaphor, target_terms in metaphor_term_sets.items():
        # convert to lower case and do an initial filter
        # lower_tokens = [t.lower() for t in orig_tokens]
        # print(tokens)
        if len(set(tokens).intersection(target_terms)) > 0:

            # Save the sentence with metadata
            outlines_by_metaphor[metaphor].append({'sent_index': sent_i, 'chyron': line})
            # Keep track of which terms are found most frequently
            term_counter_by_metaphor[metaphor].update(set(tokens).intersection(target_terms))
            is_dehumanizing = True
            category = metaphor

    yes_no_dehumanizing.append(is_dehumanizing)
    metaphor_category.append(category)

100%|██████████| 83054/83054 [00:03<00:00, 21810.47it/s]

In [129]:
df["is_dehumanizing"] = yes_no_dehumanizing

In [130]:
df["metaphor_category"] = metaphor_category

In [131]:
df

,date,network,duration(s),llm_text,show_tag,year,is_dehumanizing,metaphor_category
0,2018-01-01 11:16:46,FOXNEWSW,2,UMP LAYS OUT DEMANDS FOR DACA,FOX Friends,2018,False,<NA>
1,2018-01-01 11:18:00,FOXNEWSW,3,IMMIGRATION ON THE AGENDA,FOX Friends,2018,False,<NA>
2,2018-01-01 11:19:22,FOXNEWSW,25,DEADLINE ON DACA,FOX Friends,2018,False,<NA>
3,2018-01-01 11:19:59,FOXNEWSW,3,DACA IN THE NEW YEAR,FOX Friends,2018,False,<NA>
4,2018-01-01 13:12:39,FOXNEWSW,9,WANT TO SEE BORDER WALL BUILT,FOX Friends,2018,False,<NA>
...,...,...,...,...,...,...,...,...
83049,2026-02-27 23:53:54,MSNOW,2,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...,The Beat With Ari Melber,2026,False,<NA>
83050,2026-02-28 00:25:50,BBCNEWS,4,Iran after latest talks on immigration reforms...,BBC News,2026,False,<NA>
83051,2026-02-28 04:15:16,FOXNEWSW,3,BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,Fox News at Night,2026,False,<NA>
83052,2026-02-28 04:19:48,FOXNEWSW,4,US OLYMPIAN DEFENDS LEGAL IMMIGRATION,Fox News at Night,2026,False,<NA>
83053,2026-02-28 05:18:32,CNNW,6,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...,The Story Is With Elex Michaelson,2026,False,<NA>

In [137]:
countries = get_countries()
nationalities = get_nationalities()
regions, regionalities = get_regions_and_regionalities()

american_terms, substitutions = add_american(nationalities)
american_regional_terms, regional_subs = add_american(regionalities)

lower = True

if lower:
    countries = {country: [t.lower() for t in terms] for country, terms in countries.items()}
    nationalities = {country: [t.lower() for t in terms] for country, terms in nationalities.items()}
    american_terms = {country: [t.lower() for t in terms] for country, terms in american_terms.items()}
    regions = {region: [t.lower() for t in terms] for region, terms in regions.items()}
    regionalities = {region: [t.lower() for t in terms] for region, terms in regionalities.items()}
    american_regional_terms = {region: [t.lower() for t in terms] for region, terms in american_regional_terms.items()}

    nationality_terms = {}
    for country, terms in nationalities.items():
        nationality_terms[country] = set(terms).union(american_terms[country])

    combined_terms = {}
    for country, terms in countries.items():
        combined_terms[country] = set(terms).union(nationalities[country]).union(american_terms[country])

    combined_regional_terms = {}
    for region, terms in regions.items():
        combined_regional_terms[region] = set(terms).union(regionalities[region]).union(american_regional_terms[region])

    country_counter_by_congress = defaultdict(Counter)
    nationality_counter_by_congress = defaultdict(Counter)
    combined_counter_by_congress = defaultdict(Counter)
    region_counter_by_congress = defaultdict(Counter)
    regionality_counter_by_congress = defaultdict(Counter)
    combined_regional_counter_by_congress = defaultdict(Counter)

In [ ]:
    for line in tqdm(lines):
        line = json.loads(line)
        speech_id = line['speech_id']
        congress = int(line['congress'])
        text = line['text']
        # remove spaces and dashes from <nationality>-American terms
        for query, replacement in substitutions.items():
            text = re.sub(query, replacement, text)
        if lower:
            text = text.lower()
        tokens = set(text.split())

        for country, terms in countries.items():
            if len(tokens.intersection(terms)) > 0:
                country_counter_by_congress[country][congress] += 1
                speech_ids_by_country[country].add(speech_id)
        for country, terms in nationality_terms.items():
            if len(tokens.intersection(terms)) > 0:
                nationality_counter_by_congress[country][congress] += 1
                speech_ids_by_nationality[country].add(speech_id)
        for country, terms in combined_terms.items():
            if len(tokens.intersection(terms)) > 0:
                combined_counter_by_congress[country][congress] += 1
                speech_ids_by_nationality_plus_country[country].add(speech_id)
        for region, terms in regions.items():
            if len(tokens.intersection(terms)) > 0:
                region_counter_by_congress[region][congress] += 1
                speech_ids_by_region[region].add(speech_id)
        for region, terms in regionalities.items():
            if len(tokens.intersection(terms)) > 0:
                regionality_counter_by_congress[region][congress] += 1
                speech_ids_by_regionality[region].add(speech_id)
        for region, terms in combined_regional_terms.items():
            if len(tokens.intersection(terms)) > 0:
                combined_regional_counter_by_congress[region][congress] += 1
                speech_ids_by_region_or_regionality[region].add(speech_id)

    country_list = sorted(country_counter_by_congress)
    sums = [sum(country_counter_by_congress[country].values()) for country in country_list]

In [162]:
lines = df['llm_text']

country_mention = []
region_mention = []

for i, line in enumerate(tqdm(lines)):

    tokens = set(nltk.word_tokenize(line.lower()))
    country_mentioned = pd.NA
    region_mentioned = pd.NA

    # print(tokens)

    for country, terms in countries.items():
        if len(tokens.intersection(terms)) > 0:
            country_mentioned = country

    for country, terms in nationality_terms.items():
        if len(tokens.intersection(terms)) > 0:
            country_mentioned = country

    for country, terms in combined_terms.items():
        if len(tokens.intersection(terms)) > 0:
            country_mentioned = country

    for region, terms in regions.items():
        if len(tokens.intersection(terms)) > 0:
            region_mentioned = region

    for region, terms in regionalities.items():
        if len(tokens.intersection(terms)) > 0:
            region_mentioned = region

    for region, terms in combined_regional_terms.items():
        if len(tokens.intersection(terms)) > 0:
            region_mentioned = region

    country_mention.append(country_mentioned)
    region_mention.append(region_mentioned)

100%|██████████| 83054/83054 [00:06<00:00, 12973.30it/s]

In [163]:
df['country'] = country_mention

In [164]:
df['region'] = region_mention

In [165]:
df

,date,network,duration(s),llm_text,show_tag,year,is_dehumanizing,metaphor_category,country,region
0,2018-01-01 11:16:46,FOXNEWSW,2,UMP LAYS OUT DEMANDS FOR DACA,FOX Friends,2018,False,<NA>,<NA>,<NA>
1,2018-01-01 11:18:00,FOXNEWSW,3,IMMIGRATION ON THE AGENDA,FOX Friends,2018,False,<NA>,<NA>,<NA>
2,2018-01-01 11:19:22,FOXNEWSW,25,DEADLINE ON DACA,FOX Friends,2018,False,<NA>,<NA>,<NA>
3,2018-01-01 11:19:59,FOXNEWSW,3,DACA IN THE NEW YEAR,FOX Friends,2018,False,<NA>,<NA>,<NA>
4,2018-01-01 13:12:39,FOXNEWSW,9,WANT TO SEE BORDER WALL BUILT,FOX Friends,2018,False,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...
83049,2026-02-27 23:53:54,MSNOW,2,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...,The Beat With Ari Melber,2026,False,<NA>,<NA>,<NA>
83050,2026-02-28 00:25:50,BBCNEWS,4,Iran after latest talks on immigration reforms...,BBC News,2026,False,<NA>,Iran,<NA>
83051,2026-02-28 04:15:16,FOXNEWSW,3,BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,Fox News at Night,2026,False,<NA>,<NA>,<NA>
83052,2026-02-28 04:19:48,FOXNEWSW,4,US OLYMPIAN DEFENDS LEGAL IMMIGRATION,Fox News at Night,2026,False,<NA>,<NA>,<NA>
83053,2026-02-28 05:18:32,CNNW,6,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...,The Story Is With Elex Michaelson,2026,False,<NA>,<NA>,<NA>

In [166]:
df['region'].value_counts()

region
Latin America    3914
Europe           1706
Asia              333
Name: count, dtype: int64

In [167]:
df.to_csv("data_with_dehumanizing_labels.csv")