In [1]:
import pandas as pd

In [19]:
df_2018 = pd.read_csv("2018_clean.csv")
df_2019 = pd.read_csv("2019_clean.csv")
df_2020 = pd.read_csv("2020_clean.csv")
df_2021 = pd.read_csv("2021_clean.csv")
df_2022 = pd.read_csv("2022_clean.csv")
df_2023 = pd.read_csv("2023_clean.csv")
df_2024 = pd.read_csv("2024_clean.csv")
df_2025 = pd.read_csv("2025_clean.csv")
df_2026 = pd.read_csv("2026_clean.csv")

In [21]:
df = pd.concat([df_2018, 
                df_2019,
                df_2020,
                df_2021,
                df_2022,
                df_2023,
                df_2024,
                df_2025,
                df_2026], 
                ignore_index=True)

In [22]:
df.head()

,Unnamed: 0,date,network,duration(s),tag,original_chyron,text_cleaned,llm_text
0,0,2018-01-01 00:04:00,FOXNEWSW,4,FOXNEWSW_20180101_000000_Fox_Report_Sunday/sta...,YE ICED AS PARTS OF U.S. ENDURE DEEP FREEZE I....,YE ICED AS PARTS OF US ENDURE DEEP FREEZE I W,NaN
1,3,2018-01-01 11:16:46,FOXNEWSW,2,FOXNEWSW_20180101_110000_FOX__Friends/start/960,{UMP LAYS OUT DEMANDS FOR DACA i,UMP LAYS OUT DEMANDS FOR DACA i,UMP LAYS OUT DEMANDS FOR DACA
2,4,2018-01-01 11:18:00,FOXNEWSW,3,FOXNEWSW_20180101_110000_FOX__Friends/start/1080,IMMIGRATION ON THE AGENDA I,IMMIGRATION ON THE AGENDA I,IMMIGRATION ON THE AGENDA
3,5,2018-01-01 11:19:22,FOXNEWSW,25,FOXNEWSW_20180101_110000_FOX__Friends/start/1140,. DEADLINE ON DACA I,DEADLINE ON DACA I,DEADLINE ON DACA
4,6,2018-01-01 11:19:59,FOXNEWSW,3,FOXNEWSW_20180101_110000_FOX__Friends/start/1140,DACA IN THE NEW YEAR,DACA IN THE NEW YEAR,DACA IN THE NEW YEAR

In [23]:
df = df.dropna()

In [24]:
df

,Unnamed: 0,date,network,duration(s),tag,original_chyron,text_cleaned,llm_text
1,3,2018-01-01 11:16:46,FOXNEWSW,2,FOXNEWSW_20180101_110000_FOX__Friends/start/960,{UMP LAYS OUT DEMANDS FOR DACA i,UMP LAYS OUT DEMANDS FOR DACA i,UMP LAYS OUT DEMANDS FOR DACA
2,4,2018-01-01 11:18:00,FOXNEWSW,3,FOXNEWSW_20180101_110000_FOX__Friends/start/1080,IMMIGRATION ON THE AGENDA I,IMMIGRATION ON THE AGENDA I,IMMIGRATION ON THE AGENDA
3,5,2018-01-01 11:19:22,FOXNEWSW,25,FOXNEWSW_20180101_110000_FOX__Friends/start/1140,. DEADLINE ON DACA I,DEADLINE ON DACA I,DEADLINE ON DACA
4,6,2018-01-01 11:19:59,FOXNEWSW,3,FOXNEWSW_20180101_110000_FOX__Friends/start/1140,DACA IN THE NEW YEAR,DACA IN THE NEW YEAR,DACA IN THE NEW YEAR
5,7,2018-01-01 13:12:39,FOXNEWSW,9,FOXNEWSW_20180101_110000_FOX__Friends/start/7920,ALKIN: WANT TO SEE BORDER WALL BUILT,ALKIN WANT TO SEE BORDER WALL BUILT,WANT TO SEE BORDER WALL BUILT
...,...,...,...,...,...,...,...,...
83544,5754,2026-02-27 23:53:54,MSNOW,2,MSNOW_20260227_230000_The_Beat_With_Ari_Melber...,GOURTS GHECK SOME OF TRUMP'S ICE TACTICS EE&A&...,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...
83545,5755,2026-02-28 00:25:50,BBCNEWS,4,BBCNEWS_20260228_000000_BBC_News/start/1500,Iran after latest talks on immigration reforms...,Iran after latest talks on immigration reforms...,Iran after latest talks on immigration reforms...
83546,5756,2026-02-28 04:15:16,FOXNEWSW,3,FOXNEWSW_20260228_040000_Fox_News_at_Night/sta...,C; BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,C BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS
83547,5757,2026-02-28 04:19:48,FOXNEWSW,4,FOXNEWSW_20260228_040000_Fox_News_at_Night/sta...,U.S. OLYMPIAN DEFENDS LEGAL IMMIGRATION,US OLYMPIAN DEFENDS LEGAL IMMIGRATION,US OLYMPIAN DEFENDS LEGAL IMMIGRATION
83548,5758,2026-02-28 05:18:32,CNNW,6,CNNW_20260228_050000_The_Story_Is_With_Elex_Mi...,COLUMBIA UNIV. STUDENT SUES FEDERAL OFFICIALS ...,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...

In [25]:
df = df.drop(columns=["Unnamed: 0", "text_cleaned"])

In [26]:
df

,date,network,duration(s),tag,original_chyron,llm_text
1,2018-01-01 11:16:46,FOXNEWSW,2,FOXNEWSW_20180101_110000_FOX__Friends/start/960,{UMP LAYS OUT DEMANDS FOR DACA i,UMP LAYS OUT DEMANDS FOR DACA
2,2018-01-01 11:18:00,FOXNEWSW,3,FOXNEWSW_20180101_110000_FOX__Friends/start/1080,IMMIGRATION ON THE AGENDA I,IMMIGRATION ON THE AGENDA
3,2018-01-01 11:19:22,FOXNEWSW,25,FOXNEWSW_20180101_110000_FOX__Friends/start/1140,. DEADLINE ON DACA I,DEADLINE ON DACA
4,2018-01-01 11:19:59,FOXNEWSW,3,FOXNEWSW_20180101_110000_FOX__Friends/start/1140,DACA IN THE NEW YEAR,DACA IN THE NEW YEAR
5,2018-01-01 13:12:39,FOXNEWSW,9,FOXNEWSW_20180101_110000_FOX__Friends/start/7920,ALKIN: WANT TO SEE BORDER WALL BUILT,WANT TO SEE BORDER WALL BUILT
...,...,...,...,...,...,...
83544,2026-02-27 23:53:54,MSNOW,2,MSNOW_20260227_230000_The_Beat_With_Ari_Melber...,GOURTS GHECK SOME OF TRUMP'S ICE TACTICS EE&A&...,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...
83545,2026-02-28 00:25:50,BBCNEWS,4,BBCNEWS_20260228_000000_BBC_News/start/1500,Iran after latest talks on immigration reforms...,Iran after latest talks on immigration reforms...
83546,2026-02-28 04:15:16,FOXNEWSW,3,FOXNEWSW_20260228_040000_Fox_News_at_Night/sta...,C; BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS
83547,2026-02-28 04:19:48,FOXNEWSW,4,FOXNEWSW_20260228_040000_Fox_News_at_Night/sta...,U.S. OLYMPIAN DEFENDS LEGAL IMMIGRATION,US OLYMPIAN DEFENDS LEGAL IMMIGRATION
83548,2026-02-28 05:18:32,CNNW,6,CNNW_20260228_050000_The_Story_Is_With_Elex_Mi...,COLUMBIA UNIV. STUDENT SUES FEDERAL OFFICIALS ...,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...

In [27]:
df['show_tag'] = df['tag'].str.split("/start").str[0].str.split("_").str[3:].str.join(' ')

In [29]:
df = df.drop(columns=["tag", "original_chyron"])

In [37]:
df['date'] = df['date'].str.replace('-', '', regex=False)

df['date'] = pd.to_datetime(df['date'])

In [39]:
df['year'] = df['date'].dt.year

In [40]:
df

,date,network,duration(s),llm_text,show_tag,year
1,2018-01-01 11:16:46,FOXNEWSW,2,UMP LAYS OUT DEMANDS FOR DACA,FOX Friends,2018
2,2018-01-01 11:18:00,FOXNEWSW,3,IMMIGRATION ON THE AGENDA,FOX Friends,2018
3,2018-01-01 11:19:22,FOXNEWSW,25,DEADLINE ON DACA,FOX Friends,2018
4,2018-01-01 11:19:59,FOXNEWSW,3,DACA IN THE NEW YEAR,FOX Friends,2018
5,2018-01-01 13:12:39,FOXNEWSW,9,WANT TO SEE BORDER WALL BUILT,FOX Friends,2018
...,...,...,...,...,...,...
83544,2026-02-27 23:53:54,MSNOW,2,GOURTS GHECK SOME OF TRUMPS ICE TACTICS EEA 1I...,The Beat With Ari Melber,2026
83545,2026-02-28 00:25:50,BBCNEWS,4,Iran after latest talks on immigration reforms...,BBC News,2026
83546,2026-02-28 04:15:16,FOXNEWSW,3,BILL WOULD RESTORE BENEFITS FOR ILLEGAL ALIENS,Fox News at Night,2026
83547,2026-02-28 04:19:48,FOXNEWSW,4,US OLYMPIAN DEFENDS LEGAL IMMIGRATION,Fox News at Night,2026
83548,2026-02-28 05:18:32,CNNW,6,COLUMBIA UNIV STUDENT SUES FEDERAL OFFICIALS O...,The Story Is With Elex Michaelson,2026

In [41]:
df.to_csv("combined_years.csv")